function [AGS_PXL___Time, No_GRAINS___Time] = Plot___AGS_PXL__vs__No_Grains(Grain_Area_PXL, Number_of_grains, Properties__PrintToFile)

% [----] = Plot___AGS_PXL__vs__No_Grains(-----)
% Internal function calls: (1) NONE
% todo_A [AA-AA-20]-[AA-AA-20]: 

PrintToFile = Properties__PrintToFile{1};
FileFormat  = Properties__PrintToFile{2};
Quality     = Properties__PrintToFile{3};

AGS_PXL___Time   = zeros(numel(Grain_Area_PXL), 3);
No_GRAINS___Time = zeros(numel(Grain_Area_PXL), 1);
%---------------------------------------------------------------------------
for rset = 1:numel(Grain_Area_PXL)
    This_rset_Gsizes = Grain_Area_PXL{rset};
    AGS_PXL___Time(rset,:)   = [min(This_rset_Gsizes) max(This_rset_Gsizes) mean(This_rset_Gsizes)];
    No_GRAINS___Time(rset,:) = Number_of_grains{rset};
end
%---------------------------------------------------------------------------
figure
%---------------------------------------------------------------------------
 % Minimum GS
hp1 = plot(No_GRAINS___Time, AGS_PXL___Time(:,1), '-',...
           'Color', [140 107 177]/255,...
           'linewidth', 2,...
           'marker', 's',...
           'markeredgecolor', [129 15 124]/255,...
           'markerfacecolor', 'w',...
           'markersize',10);
hold on
%---------------------------------------------------------------------------
% Maximum GS
hp2 = plot(No_GRAINS___Time, AGS_PXL___Time(:,2), '-',...
           'Color', [065 182 196]/255,...
           'linewidth', 2,...
           'marker', 's',...
           'markeredgecolor', [8 29 88]/255,...
           'markerfacecolor', 'w',...
           'markersize',10);
%---------------------------------------------------------------------------
% Average GS
hp3 = plot(No_GRAINS___Time, AGS_PXL___Time(:,3), '-',...
           'Color', [254 178 76]/255,...
           'linewidth', 2,...
           'marker', 's',...
           'markeredgecolor', [252 78 42]/255,...
           'markerfacecolor', 'w',...
           'markersize',10);
%---------------------------------------------------------------------------
set(gca, 'XDir', 'reverse')
hleg = legend('Min GS', 'Max GS', 'Avg GS');
hxl  = xlabel({'Number of grains. (Left to Right:', 'along positive temporal coordinate)'});
hyl  = ylabel('Average grain size');
%---------------------------------------------------------------------------
set(gca, 'fontsize', 12)
set([hxl hyl], 'fontsize', 14)
set(hleg, 'fontsize', 14)
set(gca, 'linewidth', 2)
%---------------------------------------------------------------------------
% axis square
axis([min(No_GRAINS___Time) max(No_GRAINS___Time) 0 1.25*max(AGS_PXL___Time(:,2))])
% ha = annotation('textbox',[0.15 0.35 0.5 0.5],...
%                 'string',{'a'},...
%                 'interpreter', 'tex',...
%                 'edgecolor','none');
end